include::main.adoc[]

== Great Job!

Now you know the basics of writing cypher query. You are on your way to becoming a graphista! Congratulations.

Feel free to play around with the data by writing more cypher queries. If you want to learn more about cypher,
you can use one of the below resources -

1. Sign up for a forever-free, fully managed cloud database-as-a-service to continue your graph learning journey or build your first application.
   +++
   <div style="margin-top: 24px; margin-bottom: 12px;">
    <a href="https://neo4j.com/cloud/aura/?ref=sandbox-movies-guide" style="background-color: #ED1252;color: #FFFFFF; padding: 9px 24px; text-decoration: none; border-radius: 4px;" target="_blank" class="aura-cta">Start Aura Free</a></div>
  <div style="font-size: 14px;"><i>Free Forever! No credit card required!</i></div>
   +++
2. link:https://neo4j.com/docs/cypher-manual/4.0/[Cypher Manual] - detailed manual on cypher syntax
3. link:https://neo4j.com/graphacademy/online-training/v4/00-intro-neo4j-about/[Online Training - Introduction to Neo4j] - If you are new to Neo4j and like to learn through an online class, this is the best place to get started.

++++
<script>
try {
  const fn = function() {
    const mpid = encodeURIComponent(window.mixpanel && window.mixpanel.get_distinct_id());
    if(!mpid || mpid === 'undefined') {
      console.warn('no mixpanel ID found');
      return;
    };
    document.querySelectorAll(".aura-cta").forEach(function(element) {
      if (element.href.indexOf("neo4j.io") > -1) {
        const alreadyHasParam = element.href.indexOf("?") > -1;
        const mpParams = `mpid=${mpid}`;
        element.href = element.href + (alreadyHasParam ? `&${mpParams}` : `?${mpParams}`);
      }
    });
  };

  if (document.readyState === "complete") fn();
  else window.addEventListener("load", fn);
} catch(e) {
  console.warn('something wrong with mixpanel script');
}
</script>
++++